# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  # TODO: uncomment this 3 lines below to use circleci
  # before_all do
  #  setup_circle_ci
  # end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(
        type: "appstore",
    )

    # increment_build_number(
    #     build_number: latest_testflight_build_number + 1,
    #     xcodeproj: "nalam.xcodeproj",
    # )

    # add beta badge to app icon
    # add_badge

    build_app(
        workspace: "nalam.xcworkspace",
        scheme: "nalam",
        clean: true,
        export_method: "app-store",
        build_path: "./builds",
        output_directory: "./builds",
        # archive_path: "./builds"
    )

    upload_to_testflight(
        skip_waiting_for_build_processing: true,
    )
  end
end
